# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 00:25
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
                ('is_win', models.CharField(choices=[(0, 'win'), (1, 'lose')], default=-1, max_length=5)),
                ('award', models.IntegerField(default=0, verbose_name='award')),
                ('center', models.CharField(max_length=30, verbose_name='center')),
                ('p_forward', models.CharField(max_length=30, verbose_name='p_forward')),
                ('s_forward', models.CharField(max_length=30, verbose_name='s_forward')),
                ('s_guard', models.CharField(max_length=30, verbose_name='s_guard')),
                ('p_guard', models.CharField(max_length=30, verbose_name='p_guard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
