# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170508_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='static/images/default_user.png', upload_to='static/img/upload'),
        ),
    ]
