# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170508_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='center_id',
            new_name='c_id',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='p_forward_id',
            new_name='pf_id',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='p_guard_id',
            new_name='pg_id',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='s_forward_id',
            new_name='sf_id',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='s_guard_id',
            new_name='sg_id',
        ),
        migrations.AlterField(
            model_name='history',
            name='add_time',
            field=models.CharField(default=b'2017-05-09', max_length=20, verbose_name='add_time'),
        ),
    ]
