# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20170509_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='money',
            field=models.IntegerField(default=200, verbose_name='UserMoney'),
        ),
    ]
