# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_history_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='add_time',
            field=models.CharField(default=b'2017-05-11', max_length=20, verbose_name='add_time'),
        ),
        migrations.AlterField(
            model_name='history',
            name='is_win',
            field=models.CharField(default='submitted', max_length=10, verbose_name='result'),
        ),
    ]
