# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20170511_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='c_value',
            field=models.IntegerField(default=0, verbose_name='c_value'),
        ),
        migrations.AddField(
            model_name='history',
            name='pf_value',
            field=models.IntegerField(default=0, verbose_name='pf_value'),
        ),
        migrations.AddField(
            model_name='history',
            name='pg_value',
            field=models.IntegerField(default=0, verbose_name='pg_value'),
        ),
        migrations.AddField(
            model_name='history',
            name='sf_value',
            field=models.IntegerField(default=0, verbose_name='sf_value'),
        ),
        migrations.AddField(
            model_name='history',
            name='sg_value',
            field=models.IntegerField(default=0, verbose_name='sg_value'),
        ),
    ]
