# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20170511_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='c_value',
        ),
        migrations.RemoveField(
            model_name='history',
            name='pf_value',
        ),
        migrations.RemoveField(
            model_name='history',
            name='pg_value',
        ),
        migrations.RemoveField(
            model_name='history',
            name='sf_value',
        ),
        migrations.RemoveField(
            model_name='history',
            name='sg_value',
        ),
        migrations.AddField(
            model_name='history',
            name='c_score',
            field=models.IntegerField(default=0, verbose_name='c_score'),
        ),
        migrations.AddField(
            model_name='history',
            name='pf_score',
            field=models.IntegerField(default=0, verbose_name='pf_score'),
        ),
        migrations.AddField(
            model_name='history',
            name='pg_score',
            field=models.IntegerField(default=0, verbose_name='pg_score'),
        ),
        migrations.AddField(
            model_name='history',
            name='sf_score',
            field=models.IntegerField(default=0, verbose_name='sf_score'),
        ),
        migrations.AddField(
            model_name='history',
            name='sg_score',
            field=models.IntegerField(default=0, verbose_name='sg_score'),
        ),
    ]
