# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20170511_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='c_name',
            field=models.CharField(default='', max_length=30, verbose_name='Center_Name'),
        ),
        migrations.AlterField(
            model_name='history',
            name='pf_name',
            field=models.CharField(default='', max_length=30, verbose_name='PF_Name'),
        ),
        migrations.AlterField(
            model_name='history',
            name='pg_name',
            field=models.CharField(default='', max_length=30, verbose_name='PG_Name'),
        ),
        migrations.AlterField(
            model_name='history',
            name='sf_name',
            field=models.CharField(default='', max_length=30, verbose_name='SF_Name'),
        ),
        migrations.AlterField(
            model_name='history',
            name='sg_name',
            field=models.CharField(default='', max_length=30, verbose_name='SG_Name'),
        ),
    ]
