# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_history_isgameover'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_points',
            field=models.FloatField(default=0, verbose_name='TotalPoints'),
        ),
    ]
