# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_userprofile_total_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rank',
            field=models.IntegerField(default=0, verbose_name='Rank'),
        ),
    ]
