# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20170512_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='add_time',
            field=models.CharField(default=b'2017-05-13', max_length=20, verbose_name='add_time'),
        ),
        migrations.AlterField(
            model_name='history',
            name='c_score',
            field=models.FloatField(default=0, verbose_name='c_score'),
        ),
        migrations.AlterField(
            model_name='history',
            name='pf_score',
            field=models.FloatField(default=0, verbose_name='pf_score'),
        ),
        migrations.AlterField(
            model_name='history',
            name='pg_score',
            field=models.FloatField(default=0, verbose_name='pg_score'),
        ),
        migrations.AlterField(
            model_name='history',
            name='sf_score',
            field=models.FloatField(default=0, verbose_name='sf_score'),
        ),
        migrations.AlterField(
            model_name='history',
            name='sg_score',
            field=models.FloatField(default=0, verbose_name='sg_score'),
        ),
    ]
