# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
                ('message', models.CharField(max_length=500, verbose_name='message')),
            ],
            options={
                'verbose_name': 'message',
            },
        ),
    ]
