# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='name',
            field=models.CharField(max_length=20, verbose_name='name'),
        ),
    ]
