# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname1', models.CharField(default='', max_length=20, verbose_name='TeamName1')),
                ('teamname2', models.CharField(default='', max_length=20, verbose_name='TeamName2')),
                ('date', models.CharField(default=b'2017-05-08', max_length=20, verbose_name='Date')),
                ('hour', models.CharField(default=b'20:37', max_length=20, verbose_name='Hour')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Game',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('playerid', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='PlayerID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='Name')),
                ('position', models.CharField(default='', max_length=20, verbose_name='Position')),
                ('teamname', models.CharField(default='', max_length=20, verbose_name='TeamName')),
                ('value', models.IntegerField(default=0, verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Player',
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerid', models.CharField(default='00000000', max_length=10, verbose_name='PlayerID')),
                ('point', models.FloatField(default=0, verbose_name='Point')),
            ],
            options={
                'verbose_name': 'Point',
                'verbose_name_plural': 'Point',
            },
        ),
    ]
