# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20170508_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='picture',
            field=models.IntegerField(default=1, verbose_name='GamePicture'),
        ),
        migrations.AlterField(
            model_name='game',
            name='hour',
            field=models.CharField(default=b'22:22', max_length=20, verbose_name='Hour'),
        ),
    ]
