# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20170509_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='hour',
            field=models.CharField(default=b'03:54', max_length=20, verbose_name='Hour'),
        ),
    ]
