# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20170509_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.CharField(default=b'2017-05-10', max_length=20, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='game',
            name='hour',
            field=models.CharField(default=b'20:10', max_length=20, verbose_name='Hour'),
        ),
    ]
