# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_auto_20170511_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='fantasy_score',
            field=models.FloatField(default=0, verbose_name='FantasyScore'),
        ),
        migrations.AlterField(
            model_name='game',
            name='hour',
            field=models.CharField(default=b'11:57', max_length=20, verbose_name='Hour'),
        ),
    ]
