# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_auto_20170511_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_award',
            field=models.IntegerField(default=90, verbose_name='GameAward'),
        ),
        migrations.AddField(
            model_name='game',
            name='game_required',
            field=models.IntegerField(default=50, verbose_name='GameRequired'),
        ),
        migrations.AlterField(
            model_name='game',
            name='hour',
            field=models.CharField(default=b'16:32', max_length=20, verbose_name='Hour'),
        ),
    ]
