# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_auto_20170511_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='IsGameOver',
            field=models.CharField(default='false', max_length=10, verbose_name='IsGameOver'),
        ),
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.CharField(default=b'2017-05-12', max_length=20, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='game',
            name='hour',
            field=models.CharField(default=b'15:50', max_length=20, verbose_name='Hour'),
        ),
    ]
