# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_auto_20170512_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.CharField(default=b'2017-05-13', max_length=20, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='game',
            name='hour',
            field=models.CharField(default=b'11:23', max_length=20, verbose_name='Hour'),
        ),
    ]
